services:

  user-activity-producer:
    build:
      context: .
      dockerfile: producers/user_activity_producer/Dockerfile
    container_name: user-activity-producer
    env_file: .env
    environment:
      EVENTS_PER_SECOND: "10"
    restart: unless-stopped

  product-event-producer:
    build:
      context: .
      dockerfile: producers/product_event_producer/Dockerfile
    container_name: product-event-producer
    env_file: .env
    environment:
      EVENTS_PER_SECOND: "5"
    restart: unless-stopped

  order-event-producer:
    build:
      context: .
      dockerfile: producers/order_event_producer/Dockerfile
    container_name: order-event-producer
    env_file: .env
    environment:
      EVENTS_PER_SECOND: "3"
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: unless-stopped

  airflow-init:
    image: apache/airflow:2.9.3
    container_name: airflow-init
    depends_on:
      - postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    entrypoint: /bin/bash
    command:
      - -c
      - airflow db migrate && airflow users create --username admin --password admin --firstname Janak --lastname Tyagi --role Admin --email jannaktyaagi6@gmail.com

  airflow-webserver:
    image: apache/airflow:2.9.3
    container_name: airflow-webserver
    depends_on:
      - postgres
      - airflow-init
    env_file: .env
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-databricks==6.9.0"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    restart: unless-stopped

  airflow-scheduler:
    image: apache/airflow:2.9.3
    container_name: airflow-scheduler
    depends_on:
      - postgres
      - airflow-init
    env_file: .env
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-databricks==6.9.0"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
    command: scheduler
    restart: unless-stopped

volumes:
  postgres-db-volume: